FROM debian:latest

# Metadata
LABEL maintainer="mail@mclive.eu"

# Pre-build
WORKDIR /var/server
RUN apt update -y
RUN apt install -y python2.7 python-pip uwsgi python-mysqldb libmariadbclient-dev
RUN pip install virtualenv
RUN virtualenv venv
RUN source venv/bin/activate
# Copy the data
COPY ./* ./
RUN cp ./templates/uwsgi-config.ini /etc/uwsgi/apps-enabled/dpdns.ini

# Build data
RUN pip install -r requirements.txt
RUN python manage.py migrate
RUN python init_createsuperuser.py

# Run on startup
CMD uwsgi