# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpdns', '0003_auto_20170820_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='dpdns.Domains', unique=True),
        ),
    ]
